---
# tasks file for jenkins

- name: Instalando Dependencias
  yum: 
    name: "{{ item }}"
    state: latest
  when:
    - ansible_os_family == "RedHat"
  loop:
    - curl
    - libselinux-python 

- name: Adicionando o repositorio do Jenkins
  get_url:
    url: 'http://pkg.jenkins-ci.org/redhat/jenkins.repo'
    dest: /etc/yum.repos.d/jenkins.repo
    force: yes
    validate_certs: no
  when:
    - ansible_os_family == "RedHat"
  register: repo
  
- rpm_key: 
    state: present
    key: 'http://jenkins-ci.org/redhat/jenkins-ci.org.key'
    validate_certs: no
  when:
    - ansible_os_family == "RedHat"
    - repo is success
  register: rpmkey
  
- name: Instalando Jenkins
  yum: 
    name: jenkins 
    state: latest
    enablerepo: epel
  when:
    - ansible_os_family == "RedHat"
    - repo is success
    - rpmkey is success
  register: PACKAGE
  notify: 
    - Start Jenkins
...
