---
# tasks file for jenkins
- name: Adicionando o repositorio do Jenkins
  get_url:
    url: 'http://pkg.jenkins-ci.org/redhat/jenkins.repo'
    dest: /etc/yum.repos.d/jenkins.repo
  when: ( ansible_os_family == "RedHat" )
  register: repo
  
- rpm_key: 
    state: present
    key: 'http://jenkins-ci.org/redhat/jenkins-ci.org.key'
    validate_certs: no
  when:
    - ansible_os_family == "RedHat"
    - repo is success
  register: rpmkey
  
- name: Instalando Jenkins
  yum: 
    name: jenkins 
    state: latest
  when:
    - ansible_os_family == "RedHat"
    - rpmkey is success
...
