---
# tasks file for jenkins


# Import Variable
- name: Include OS-Specific variables
  include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks
- name: Instalando o Jenkins para "{{ ansible_distribution }}" versão "{{ ansible_distribution_major_version }}"
  include_tasks: conf2{{ ansible_distribution }}.yml
...
